### ISSUE TITLE
What is 'pin spacer' element?

### ISSUE THREAD

**Issue by fredbergwitz** [codrops/ScrollBasedLayoutAnimations#3]
Great work! Perhaps I'm retarded but I can't seem to figure out where, when and how 'pin-spacer' is created?

<img width="366" alt="SCR-20240823-mzzr" src="https://github.com/user-attachments/assets/78a3b197-a07f-468e-a374-3a568d52c856">

**Comment by crnacura** [comment]
Thank you Fred! That's part of the GSAP ScrollTrigger's pinning: https://gsap.com/docs/v3/Plugins/ScrollTrigger/?page=1#pinSpacer
